/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import Objetos.CrudE;

/**
 *
 * @author migue
 */
public class BorrarE extends javax.swing.JInternalFrame {

    /**
     * Creates new form BorrarE
     */
    int nie;
    public BorrarE(int nie) {
        initComponents();
        this.nie= nie;
        CrudE oest = new CrudE();
        oest.mostrar(nie);
        String ni = nie+"";
        txtNie.setText(ni);
        txtNombreE.setText(oest.getNombre());
        txtApellidoE.setText(oest.getApellido());
        int edad = oest.getEdad();
        String eda = edad+"";
        txtEdadE.setText(eda);
        cmbSexoE.setSelectedItem(oest.getSexo());
        cmbxGrado.setSelectedItem(oest.getGrado());
        cmbxZona.setSelectedItem(oest.getZona());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSexoE = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbxGrado = new javax.swing.JComboBox<>();
        cmbxZona = new javax.swing.JComboBox<>();
        txtNombreE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEdadE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtApellidoE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNie = new javax.swing.JTextField();
        bttnBorrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        cmbSexoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSexoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cmbSexoE.setEnabled(false);
        getContentPane().add(cmbSexoE);
        cmbSexoE.setBounds(370, 330, 60, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("NIE: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 90, 70, 22);

        cmbxGrado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbxGrado.setEnabled(false);
        getContentPane().add(cmbxGrado);
        cmbxGrado.setBounds(370, 380, 70, 23);

        cmbxZona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R", "U" }));
        cmbxZona.setEnabled(false);
        getContentPane().add(cmbxZona);
        cmbxZona.setBounds(370, 430, 70, 23);

        txtNombreE.setEditable(false);
        txtNombreE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtNombreE);
        txtNombreE.setBounds(370, 150, 161, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Edad:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 270, 70, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Apellidos: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 210, 110, 22);

        txtEdadE.setEditable(false);
        txtEdadE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtEdadE);
        txtEdadE.setBounds(370, 270, 161, 30);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 26)); // NOI18N
        jLabel1.setText("Eliminar Elemento en Estudiante");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 570, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 330, 60, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 150, 100, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Zona de vivienda:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 430, 170, 22);

        txtApellidoE.setEditable(false);
        txtApellidoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtApellidoE);
        txtApellidoE.setBounds(370, 210, 161, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Grado:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 380, 70, 22);

        txtNie.setEditable(false);
        txtNie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtNie);
        txtNie.setBounds(370, 90, 161, 30);

        bttnBorrar.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        bttnBorrar.setText("Borrar");
        bttnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnBorrar);
        bttnBorrar.setBounds(340, 499, 97, 52);

        setBounds(375, 75, 777, 620);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBorrarActionPerformed
        CrudE borrar = new CrudE();
        borrar.eliminar(nie);
    }//GEN-LAST:event_bttnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnBorrar;
    public javax.swing.JComboBox<String> cmbSexoE;
    public javax.swing.JComboBox<String> cmbxGrado;
    public javax.swing.JComboBox<String> cmbxZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txtApellidoE;
    public static javax.swing.JTextField txtEdadE;
    public static javax.swing.JTextField txtNie;
    public static javax.swing.JTextField txtNombreE;
    // End of variables declaration//GEN-END:variables
}
