/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import static JFrames.FrmInicio.escritorio;
import Objetos.BusquedaD;
import java.awt.Dimension;

/**
 *
 * @author migue
 */
public class BuscarD extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarD
     */
    public BuscarD() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSexo = new javax.swing.JButton();
        cmbxSexoD = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        datos.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(datos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 808, 367);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel1.setText("Buscar elementos en Docente");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 30, 470, 32);

        btnSexo.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        btnSexo.setText("Buscar por sexo");
        btnSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSexoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSexo);
        btnSexo.setBounds(150, 470, 130, 40);

        cmbxSexoD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxSexoD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(cmbxSexoD);
        cmbxSexoD.setBounds(290, 480, 50, 23);

        setBounds(340, 110, 878, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSexoActionPerformed

        String sexo =cmbxSexoD.getSelectedItem().toString();
        BusquedaD buscar = new BusquedaD();
        buscar.docMasoFem(datos, sexo);

    }//GEN-LAST:event_btnSexoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSexo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbxSexoD;
    public javax.swing.JTable datos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
