/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import Objetos.ComparadoresE;
import Objetos.CrudE;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class BuscarE extends javax.swing.JInternalFrame {

    /**
     * Creates new form MEstudiantes
     */
    public BuscarE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        editarE = new javax.swing.JButton();
        Borrarbttn = new javax.swing.JButton();
        cmbSexoE = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("MostrarEstudiantes");
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel4.setText("Buscar Datos de Estudiantes en la Base");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 30, 590, 40);

        datos.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(datos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 850, 350);

        btnBuscar.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        btnBuscar.setText("Buscar Sexo");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(170, 460, 120, 47);

        editarE.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        editarE.setText("Editar\n Selección"); // NOI18N
        editarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEActionPerformed(evt);
            }
        });
        getContentPane().add(editarE);
        editarE.setBounds(430, 480, 140, 25);

        Borrarbttn.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        Borrarbttn.setText("Borrar Selección");
        Borrarbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarbttnActionPerformed(evt);
            }
        });
        getContentPane().add(Borrarbttn);
        Borrarbttn.setBounds(610, 470, 140, 39);

        cmbSexoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSexoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(cmbSexoE);
        cmbSexoE.setBounds(310, 470, 50, 30);

        setBounds(340, 110, 879, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String sexo =cmbSexoE.getSelectedItem().toString();
        ComparadoresE buscar = new ComparadoresE();
        buscar.femoMas(datos, sexo);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void editarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEActionPerformed
        try{
        int nie;
        DefaultTableModel tm = (DefaultTableModel) datos.getModel();
        nie=Integer.parseInt(String.valueOf(tm.getValueAt(datos.getSelectedRow(), 0)));
        EditarE editar = new EditarE(nie);
        FrmInicio.escritorio.add(editar);
        editar.toFront();
        editar.show();}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento \n"+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarEActionPerformed

    private void BorrarbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarbttnActionPerformed
        
    }//GEN-LAST:event_BorrarbttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrarbttn;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JComboBox<String> cmbSexoE;
    public javax.swing.JTable datos;
    private javax.swing.JButton editarE;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
