/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import Objetos.CrudE;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class EditarE extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarE
     */
    int nie;
    public EditarE(int nie) {
        initComponents();
        this.nie= nie;
        CrudE oest = new CrudE();
        oest.mostrar(nie);
        String ni = nie+"";
        txtNie.setText(ni);
        txtNombreE.setText(oest.getNombre());
        txtApellidos.setText(oest.getApellido());
        int edad = oest.getEdad();
        String eda = edad+"";
        txtEdad.setText(eda);
        comboboxSexoE.setSelectedItem(oest.getSexo());
        comboboxgrado.setSelectedItem(oest.getGrado());
        comboboxzonaE.setSelectedItem(oest.getZona());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bttnEditar = new javax.swing.JButton();
        comboboxzonaE = new javax.swing.JComboBox<>();
        txtApellidos = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboboxgrado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboboxSexoE = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("EditarEstudiante");
        getContentPane().setLayout(null);

        txtNombreE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreE);
        txtNombreE.setBounds(340, 130, 173, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Sexo: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 310, 59, 22);

        bttnEditar.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        bttnEditar.setText("Editar");
        bttnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnEditar);
        bttnEditar.setBounds(330, 490, 90, 50);

        comboboxzonaE.setEditable(true);
        comboboxzonaE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboboxzonaE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R", "U" }));
        getContentPane().add(comboboxzonaE);
        comboboxzonaE.setBounds(350, 410, 87, 30);

        txtApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidos);
        txtApellidos.setBounds(340, 190, 173, 30);

        txtEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdad);
        txtEdad.setBounds(340, 250, 173, 30);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel4.setText("Editar Elemento de la base en Estudiantes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 10, 640, 42);

        txtNie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNieKeyTyped(evt);
            }
        });
        getContentPane().add(txtNie);
        txtNie.setBounds(340, 70, 173, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Zona de vivienda:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 420, 170, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Edad:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 260, 59, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nie:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 80, 42, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Grado:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 370, 59, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 140, 102, 22);

        comboboxgrado.setEditable(true);
        comboboxgrado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboboxgrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        getContentPane().add(comboboxgrado);
        comboboxgrado.setBounds(350, 360, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 200, 90, 20);

        comboboxSexoE.setEditable(true);
        comboboxSexoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboboxSexoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(comboboxSexoE);
        comboboxSexoE.setBounds(350, 300, 70, 30);

        setBounds(375, 75, 777, 620);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEditarActionPerformed
        try{
        int NIE=Integer.parseInt(txtNie.getText());
        String nombre =txtNombreE.getText();
        String apellido=txtApellidos.getText();
        int edad =Integer.parseInt(txtEdad.getText());
        String sexo =comboboxSexoE.getSelectedItem().toString();
        String grado=comboboxgrado.getSelectedItem().toString();
        String zona=comboboxzonaE.getSelectedItem().toString();
        CrudE obEstudiante = new CrudE();
        obEstudiante.editar(NIE, nombre,apellido,edad,sexo,grado,zona);}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "No se pueden dejar campos vacíos \n"+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnEditarActionPerformed

    private void txtNieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNieKeyTyped
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtNieKeyTyped

    private void txtNombreEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEKeyTyped
    int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
    boolean acentos = key >=130 && key <=250;
            
     if (!(minusculas || mayusculas || espacio || acentos))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtNombreEKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
    int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
    boolean acentos = key >=130 && key <=250;
            
     if (!(minusculas || mayusculas || espacio || acentos))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtEdadKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnEditar;
    public static javax.swing.JComboBox<String> comboboxSexoE;
    public static javax.swing.JComboBox<String> comboboxgrado;
    public static javax.swing.JComboBox<String> comboboxzonaE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JTextField txtApellidos;
    public static javax.swing.JTextField txtEdad;
    public static javax.swing.JTextField txtNie;
    public static javax.swing.JTextField txtNombreE;
    // End of variables declaration//GEN-END:variables
}
