/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import Objetos.CrudE;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class Estudiantes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estudiantes
     */
    public Estudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSexoE = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbxGrado = new javax.swing.JComboBox<>();
        cmbxZona = new javax.swing.JComboBox<>();
        txtNombreE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEdadE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtApellidoE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        guardarE1 = new javax.swing.JButton();
        txtNie = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("GuardarEstudiantes");
        getContentPane().setLayout(null);

        cmbSexoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSexoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(cmbSexoE);
        cmbSexoE.setBounds(370, 330, 60, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("NIE: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 90, 70, 22);

        cmbxGrado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        getContentPane().add(cmbxGrado);
        cmbxGrado.setBounds(370, 380, 70, 23);

        cmbxZona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R", "U" }));
        getContentPane().add(cmbxZona);
        cmbxZona.setBounds(370, 430, 70, 23);

        txtNombreE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreE);
        txtNombreE.setBounds(370, 150, 161, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Edad:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 270, 70, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Apellidos: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 210, 110, 22);

        txtEdadE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEdadE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadEKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdadE);
        txtEdadE.setBounds(370, 270, 161, 30);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 26)); // NOI18N
        jLabel1.setText("Estudiante");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 20, 240, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 330, 60, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 150, 100, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Zona de vivienda:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 430, 170, 22);

        txtApellidoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellidoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoEKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidoE);
        txtApellidoE.setBounds(370, 210, 161, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Grado:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 380, 70, 22);

        guardarE1.setBackground(new java.awt.Color(255, 204, 204));
        guardarE1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        guardarE1.setText("Guardar");
        guardarE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarE1ActionPerformed(evt);
            }
        });
        getContentPane().add(guardarE1);
        guardarE1.setBounds(330, 510, 110, 50);

        txtNie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNieKeyTyped(evt);
            }
        });
        getContentPane().add(txtNie);
        txtNie.setBounds(370, 90, 161, 30);

        setBounds(375, 75, 777, 620);
    }// </editor-fold>//GEN-END:initComponents

    private void guardarE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarE1ActionPerformed
        try{
        int NIE=Integer.parseInt(txtNie.getText());
        String nombre =txtNombreE.getText();
        String apellido=txtApellidoE.getText();
        int edad =Integer.parseInt(txtEdadE.getText());
        String sexo =cmbSexoE.getSelectedItem().toString();
        String grado=cmbxGrado.getSelectedItem().toString();
        String zona=cmbxZona.getSelectedItem().toString();
        CrudE ObEstudiante=new CrudE();
        ObEstudiante.insertar(NIE, nombre,apellido,edad,sexo,grado,zona);}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "No se pueden dejar campos vacíos \n"+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarE1ActionPerformed

    private void txtNieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNieKeyTyped
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtNieKeyTyped

    private void txtNombreEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEKeyTyped
        int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
    boolean acentos = key >=130 && key <=250;
            
     if (!(minusculas || mayusculas || espacio || acentos))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtNombreEKeyTyped

    private void txtApellidoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoEKeyTyped
    int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
    boolean acentos = key >=130 && key <=250;
            
     if (!(minusculas || mayusculas || espacio || acentos))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtApellidoEKeyTyped

    private void txtEdadEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadEKeyTyped
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtEdadEKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cmbSexoE;
    public javax.swing.JComboBox<String> cmbxGrado;
    public javax.swing.JComboBox<String> cmbxZona;
    private javax.swing.JButton guardarE1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txtApellidoE;
    public static javax.swing.JTextField txtEdadE;
    public static javax.swing.JTextField txtNie;
    public static javax.swing.JTextField txtNombreE;
    // End of variables declaration//GEN-END:variables
}
