/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import Objetos.CrudD;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class FrmDocentes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDocentes
     */
    public FrmDocentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAsig = new javax.swing.JTextField();
        cmbxSexoD = new javax.swing.JComboBox<>();
        txtEdadD = new javax.swing.JTextField();
        bttnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Docentes");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel1.setText("Docente");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 30, 150, 32);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DUI:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 90, 40, 22);

        txtDui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuiKeyTyped(evt);
            }
        });
        getContentPane().add(txtDui);
        txtDui.setBounds(370, 90, 133, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombres:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 150, 90, 25);

        txtApellidoD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellidoD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoDKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidoD);
        txtApellidoD.setBounds(370, 210, 133, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Edad: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 270, 70, 25);

        txtNombreD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreDKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreD);
        txtNombreD.setBounds(370, 150, 133, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Apellidos:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 210, 100, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Sexo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 400, 91, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Asignatura:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 330, 120, 25);

        txtAsig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAsig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAsigKeyTyped(evt);
            }
        });
        getContentPane().add(txtAsig);
        txtAsig.setBounds(370, 330, 133, 30);

        cmbxSexoD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxSexoD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(cmbxSexoD);
        cmbxSexoD.setBounds(380, 400, 50, 23);

        txtEdadD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEdadD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadDKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdadD);
        txtEdadD.setBounds(370, 270, 133, 30);

        bttnGuardar.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        bttnGuardar.setText("Guardar");
        bttnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnGuardar);
        bttnGuardar.setBounds(340, 470, 110, 50);

        setBounds(375, 75, 777, 620);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGuardarActionPerformed
        try{
        int dui=Integer.parseInt(txtDui.getText());
        String nombre =txtNombreD.getText();
        String apellido=txtApellidoD.getText();
        int edad =Integer.parseInt(txtEdadD.getText());
        String asignatura = txtAsig.getText();
        String sexo =cmbxSexoD.getSelectedItem().toString();
        CrudD obDocente= new CrudD();
        obDocente.insertar(dui, nombre, apellido, edad, asignatura, sexo);
        txtDui.setText("");
        txtNombreD.setText("");
        txtApellidoD.setText("");
        txtEdadD.setText("");
        txtAsig.setText("");
        cmbxSexoD.setSelectedIndex(0);}
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se pueden dejar campos vacíos \n"+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnGuardarActionPerformed

    private void txtDuiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuiKeyTyped
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtDuiKeyTyped

    private void txtEdadDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadDKeyTyped
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtEdadDKeyTyped

    private void txtNombreDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDKeyTyped
    int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
    boolean acentos = key >=130 && key <=250;
            
     if (!(minusculas || mayusculas || espacio || acentos))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtNombreDKeyTyped

    private void txtApellidoDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoDKeyTyped
     int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
    boolean acentos = key >=130 && key <=233;
    boolean otros = key >=130 && key <=250;
            
     if (!(minusculas || mayusculas || espacio || acentos|| otros))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtApellidoDKeyTyped

    private void txtAsigKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAsigKeyTyped
    int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
    boolean acentos = key >=130 && key <=250;
            
     if (!(minusculas || mayusculas || espacio || acentos))
    {
        evt.consume();
    }
    }//GEN-LAST:event_txtAsigKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnGuardar;
    private javax.swing.JComboBox<String> cmbxSexoD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellidoD;
    private javax.swing.JTextField txtAsig;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtEdadD;
    private javax.swing.JTextField txtNombreD;
    // End of variables declaration//GEN-END:variables
}
