/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import Objetos.CrudD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class MDocentes extends javax.swing.JInternalFrame {

    /**
     * Creates new form MDocentes
     */
    public MDocentes() {
        initComponents();
        CrudD ver = new CrudD();
        ver.mostrar(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        editarbttn = new javax.swing.JButton();
        mostrarbttn = new javax.swing.JButton();
        borrarbttn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MostrarDocentes");
        getContentPane().setLayout(null);

        datos.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(datos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 94, 808, 344);

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel5.setText("Ver elementos en la base de Docentes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 30, 579, 29);

        editarbttn.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        editarbttn.setText("Editar selección");
        editarbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbttnActionPerformed(evt);
            }
        });
        getContentPane().add(editarbttn);
        editarbttn.setBounds(370, 470, 133, 50);

        mostrarbttn.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        mostrarbttn.setText("Actualizar");
        mostrarbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarbttnActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarbttn);
        mostrarbttn.setBounds(220, 470, 100, 40);

        borrarbttn.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        borrarbttn.setText("Borrar Selección");
        borrarbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbttnActionPerformed(evt);
            }
        });
        getContentPane().add(borrarbttn);
        borrarbttn.setBounds(550, 470, 137, 50);

        setBounds(340, 110, 879, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void editarbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbttnActionPerformed
        try{
        int dui;
        DefaultTableModel tm = (DefaultTableModel) datos.getModel();
        dui=Integer.parseInt(String.valueOf(tm.getValueAt(datos.getSelectedRow(), 0)));
        EditarD editar = new EditarD(dui);
        FrmInicio.escritorio.add(editar);
        editar.toFront();
        editar.show();}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento \n"+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarbttnActionPerformed

    private void mostrarbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarbttnActionPerformed

        CrudD ver = new CrudD();
        ver.mostrar(datos);
    }//GEN-LAST:event_mostrarbttnActionPerformed

    private void borrarbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbttnActionPerformed
        try{
        int dui;
        DefaultTableModel tm = (DefaultTableModel) datos.getModel();
        dui=Integer.parseInt(String.valueOf(tm.getValueAt(datos.getSelectedRow(), 0)));
        BorrarD borrar = new BorrarD(dui);
        FrmInicio.escritorio.add(borrar);
        borrar.toFront();
        borrar.show();}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento \n"+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_borrarbttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarbttn;
    public javax.swing.JTable datos;
    private javax.swing.JButton editarbttn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarbttn;
    // End of variables declaration//GEN-END:variables
}
