/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JFrames;

import Objetos.CrudE;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class MEstudiantes extends javax.swing.JInternalFrame {

    /**
     * Creates new form MEstudiantes
     */
    public MEstudiantes() {
        initComponents();
        CrudE obEstudiante = new CrudE();
        obEstudiante.mostrar(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        mostrarbttn = new javax.swing.JButton();
        editarE = new javax.swing.JButton();
        Borrarbttn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("MostrarEstudiantes");
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel4.setText("Ver Datos de Estudiantes en la Base");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 30, 541, 40);

        datos.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(datos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 850, 350);

        mostrarbttn.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        mostrarbttn.setText("Actualizar");
        mostrarbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarbttnActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarbttn);
        mostrarbttn.setBounds(170, 460, 100, 47);

        editarE.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        editarE.setText("Editar\n Selección"); // NOI18N
        editarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEActionPerformed(evt);
            }
        });
        getContentPane().add(editarE);
        editarE.setBounds(340, 470, 140, 25);

        Borrarbttn.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        Borrarbttn.setText("Borrar Selección");
        Borrarbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarbttnActionPerformed(evt);
            }
        });
        getContentPane().add(Borrarbttn);
        Borrarbttn.setBounds(510, 470, 140, 39);

        setBounds(340, 110, 879, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarbttnActionPerformed

        CrudE obEstudiante = new CrudE();
        obEstudiante.mostrar(datos);
    }//GEN-LAST:event_mostrarbttnActionPerformed

    private void editarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEActionPerformed
        try{
        int nie=0;
        DefaultTableModel tm = (DefaultTableModel) datos.getModel();
        nie=Integer.parseInt(String.valueOf(tm.getValueAt(datos.getSelectedRow(), 0)));
        EditarE editar = new EditarE(nie);
        FrmInicio.escritorio.add(editar);
        editar.toFront();
        editar.show();}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento \n"+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarEActionPerformed

    private void BorrarbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarbttnActionPerformed
        try{
        int nie=0;
        DefaultTableModel tm = (DefaultTableModel) datos.getModel();
        nie=Integer.parseInt(String.valueOf(tm.getValueAt(datos.getSelectedRow(), 0)));
        BorrarE borrar = new BorrarE(nie);
        FrmInicio.escritorio.add(borrar);
        borrar.toFront();
        borrar.show();}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento \n"+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BorrarbttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrarbttn;
    public javax.swing.JTable datos;
    private javax.swing.JButton editarE;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton mostrarbttn;
    // End of variables declaration//GEN-END:variables
}
